on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n ticketingacr -g ticketingacra10d-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n ticketingacr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n ticketingacr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n ticketingacr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: ticketingacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/auth" -f  "auth/Dockerfile" -t ticketingacr.azurecr.io/ticketing:${{ github.sha }}
        docker push ticketingacr.azurecr.io/ticketing:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_ticketing_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ticketing5d70 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ticketing5d70`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ticketing5d70
        container-registry-url: ticketingacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: ticketingdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: ticketing5d70
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ticketingacr.azurecr.io/ticketing:${{ github.sha }}
        imagepullsecrets: |
          ticketingdockerauth